# Generated by Django 3.1 on 2020-08-19 15:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 8, 19, 15, 25, 7, 170170, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
